/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

/**
 *
 * @author tomas
 */
public class Panel7 extends javax.swing.JPanel {

    /**
     * Creates new form Panel7
     */
    public Panel7() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPasswordField2 = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();

        setLayout(null);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Codigo:");
        add(jLabel1);
        jLabel1.setBounds(66, 45, 37, 14);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nome:");
        add(jLabel2);
        jLabel2.setBounds(66, 65, 31, 14);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Email:");
        add(jLabel3);
        jLabel3.setBounds(66, 88, 28, 14);

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Confirme a senha:");
        add(jLabel5);
        jLabel5.setBounds(66, 140, 88, 14);

        jButton1.setFont(new java.awt.Font("TypoUpright BT", 0, 48)); // NOI18N
        jButton1.setText("Confirmar");
        add(jButton1);
        jButton1.setBounds(530, 484, 180, 50);

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("10159871");
        add(jLabel6);
        jLabel6.setBounds(113, 45, 48, 14);

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Joao Silva");
        add(jLabel7);
        jLabel7.setBounds(115, 65, 48, 14);

        jTextField1.setText("joao@alunos.utfpr.edu.br");
        add(jTextField1);
        jTextField1.setBounds(112, 85, 132, 20);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nova Senha:");
        add(jLabel4);
        jLabel4.setBounds(66, 114, 62, 14);

        jPasswordField1.setText("jPasswordField1");
        add(jPasswordField1);
        jPasswordField1.setBounds(161, 111, 111, 20);

        jPasswordField2.setText("jPasswordField2");
        add(jPasswordField2);
        jPasswordField2.setBounds(164, 137, 111, 20);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Fundo Geral.jpg"))); // NOI18N
        add(jLabel8);
        jLabel8.setBounds(0, -30, 780, 610);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
