/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import BandodeDados.*;
import ru.*;


/**
 *
 * @author Tomás Abril
 */

public class Principal extends javax.swing.JPanel {

    public static Janela mainInstance;
    
    /**
     * Creates new form Panel1
     */
    public Principal(Janela instance) {
        initComponents();
        
        mainInstance = instance;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jLabel8 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        textField2 = new java.awt.TextField();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jDialog1.setLocation(new java.awt.Point(500, 250));
        jDialog1.setSize(new java.awt.Dimension(360, 180));
        jDialog1.getContentPane().setLayout(null);

        jLabel8.setFont(new java.awt.Font("Arial Unicode MS", 1, 18)); // NOI18N
        jLabel8.setText("Senha:");
        jDialog1.getContentPane().add(jLabel8);
        jLabel8.setBounds(40, 66, 63, 25);

        jPasswordField1.setText("jPasswordField1");
        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        jDialog1.getContentPane().add(jPasswordField1);
        jPasswordField1.setBounds(143, 72, 156, 20);

        jLabel9.setFont(new java.awt.Font("Arial Unicode MS", 1, 18)); // NOI18N
        jLabel9.setText("Login:");
        jDialog1.getContentPane().add(jLabel9);
        jLabel9.setBounds(40, 35, 55, 25);

        textField2.setText("Atendente1");
        textField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField2ActionPerformed(evt);
            }
        });
        jDialog1.getContentPane().add(textField2);
        textField2.setBounds(143, 35, 156, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Untitled-2 - Copia.png"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(342, 142));
        jLabel1.setMinimumSize(new java.awt.Dimension(342, 142));
        jLabel1.setPreferredSize(new java.awt.Dimension(342, 142));
        jDialog1.getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 420, 140);

        setLayout(null);

        jButton2.setFont(new java.awt.Font("Arial Unicode MS", 1, 18)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Cliente.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2);
        jButton2.setBounds(410, 300, 220, 120);

        jButton3.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 36)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Atendente.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3);
        jButton3.setBounds(170, 300, 220, 120);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Inicial.png"))); // NOI18N
        add(jLabel2);
        jLabel2.setBounds(0, 0, 800, 560);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        mainInstance.mostrarCarta("card3");

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        jDialog1.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        jDialog1.setVisible(false);
        mainInstance.mostrarCarta("card2");
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void textField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jPasswordField1;
    private java.awt.TextField textField2;
    // End of variables declaration//GEN-END:variables
}
